version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
    - "5432:5432"
    - "9999:9999"
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - PGDATA=/PGDATA
    volumes:
    - ./postgres-data:/PGDATA

  python:
    build:
      ./python
    container_name: python
    volumes:
      - ./python:/app
    environment:
      - database=postgres
      - user=postgres
      - password=postgres
    entrypoint: bash
    tty: true