version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - env_variables
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  python:
    image: python:3.8
    container_name: python
    volumes:
      - ./python:/home/
      - ./env_variables:/home/env_variables
      - ./python.sh:/python.sh
    tty: true